openapi: 3.0.0
info:
  title: Tasker Service
  description: A simple service that allows get operation tracking advertisement web service .
  version: 0.0.1
servers:
  - url: "http://localhost:1984"
    description: Local dev server
paths:
  /ad:
    get:
      summary: Retrieves the entry for adservice randomly
      parameters:
        - name: randomly
          in: path
          required: true
          description: Randomly retrieve an advertisement.
          schema:
            type: number
      responses:
        "200":
          description:  Returns an advertisement 
          content:
            application/json:
              schema:
                $ref: "none"                
  
     

       

   