openapi: 3.0.0
info:
  title: Tasker Service
  description: A simple service that allows CRUD operations tracking task web service .
  version: 0.0.1
servers:
  - url: "http://localhost:6107"
    description: Local dev server
paths:
  /task:
    post:
      summary: Creates a new task entry with the given information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        "201":
          description: An console object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
       
    get:
      summary: Retrieves all tasks.
      responses:
        "200":
          description: All task object 
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
  /task/{id}:
    get:
      summary: Retrieves the entry for task by manufacturer
      parameters:
        - name: id
          in: path
          required: true
          description: Category of task you would like to retrieve.
          schema:
            type: number
      responses:
        "200":
          description:  Console object matching given Manufacturer
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"                
  /task/{category}:
    get:
      summary: Retrieves the entry for task by manufacturer
      parameters:
        - name: category
          in: path
          required: true
          description: Category of task you would like to retrieve.
          schema:
            type: string
      responses:
        "200":
          description:  Console object matching given Manufacturer
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"  
                
components:
  schemas:
    Task:
      properties:
        id:
          type: integer
        description:
          type: string
        createDate:
          type: string
        dueDate:
          type: string
        category:
          type: string
        
      required:
        - description
        - createDate
        - duedate
        - category
       

   